### ISSUE TITLE
Draft of a Hiera configuration

### ISSUE THREAD

**Issue by bibigon812** [bibigon812/bibigon812-quagga#13]
@m4ce What are you think about BGP, AF and neighbours? I don't like what's written below, but I couldn't think of anything better.

```
# bgp router parameters
quagga::bgp::router:
    65000:
        import_check: true
        default_ipv4_unicast: false
        router_id: 10.255.255.1
        redistribute:
            - ospf route-map BGP_FROM_OSPF
        address_family:
            ipv4_unicast:
                maximum_ebgp_paths: 2
                maximum_ibgp_paths: 10
                networks:
                    - 1.1.1.0/24
                    - 1.1.2.0/24
            ipv4_multicast:
                networks:
                    - 230.0.0.0/24
                    - 230.0.255.0/24
            ipv6_unicast:
                networks:
                    - 1::/64
                    - 2::/64

# bgp peer parameters
quagga::bgp::peers:
    CLIENTS:
        passive: true
        peer_group: true
        address_family:
            ipv4_unicast:
                activate: true
    INTERNAL:
        local_as: 65000
        peer_group: true
        remote_as: 65000
        shutdown: false
        update_source: 192.168.0.1
        address_family:
            ipv4_unicast:
                activate: true
                alliw_as_in: 1
                next_hop_self: true
    172.16.0.2:
        remote_as: 65001
        address_family:
            ipv4_unicast:
                activate: true
    192.168.0.2:
        peer_group: INTERNAL
        address_family:
            ipv4_unicast:
                activate: true
            ipv4_multicast:
                activate: true
            ipv6_unicast:
                activate: true
```

**Comment by m4ce** [comment]
@bibigon812, I am just putting together some changes. Let me send you a PR and I will briefly described my approach.

**Comment by bibigon812** [comment]
@m4ce, I'm impressed with how quickly you fixed my ugly code. But I return to the topic of BGP, AF and neighbours. There are 3 groups of setting in the bgp router.

- general bgp settings
- address family settings
- neighbour settings

The question is how to design the best configuration?

[bgp_af_peer.pdf](https://github.com/bibigon812/bibigon812-quagga/files/1114253/bgp_af_peer.pdf)

**Comment by m4ce** [comment]
@bibigon812, the idea would be to define all those settings in Hiera as follows:

For instance:

```yaml
---
quagga::bgp::router:
    65000:
        import_check: true
        default_ipv4_unicast: false
        router_id: 10.255.255.1
        redistribute:
            - ospf route-map BGP_FROM_OSPF
quagga::bgp::peers:
    "65000 CLIENTS":
        passive: true
        peer_group: true
    "65000 INTERNAL":
        local_as: 65000
        peer_group: true
        remote_as: 65000
        shutdown: false
        update_source: 192.168.0.1
    "65000 172.16.0.2":
        remote_as: 65001
    "65000 192.168.0.2":
        peer_group: INTERNAL
quagga::bgp::as_paths:
    FROM_AS100:
        rules:
            - 'permit _100$'
quagga::bgp::community_lists:
  100:
    rules:
      - 'permit 65000:101'
      - 'permit 65000:102'
      - 'permit 65000:103'
  200:
    rules:
      - 'permit 65000:201'
      - 'permit 65000:202'
quagga::bgp::address_families:
  "65000 ipv4_unicast":
    maximum_ebgp_paths: 2
    maximum_ibgp_paths: 10
    networks:
      - 1.1.1.0/24
      - 1.1.2.0/24
  "65000 ipv4_multicast":
    networks:
      - 230.0.0.0/24
      - 230.0.255.0/24
  "65000 ipv6_unicast":
    networks:
      - 1::/64
      - 2::/64
```

**Comment by bibigon812** [comment]
@m4ce , The resource quagga_bgp_router has only one instance. I guess we can skip an AS number in other resources.

**Comment by m4ce** [comment]
Indeed - Perhaps, we can do something like this:

```yaml
quagga::bgp::as_number: 65000
quagga::bgp::router:
  import_check: true
  default_ipv4_unicast: false
  router_id: 10.255.255.1
  redistribute:
    - ospf route-map BGP_FROM_OSPF
quagga::bgp::peers:
    CLIENTS:
        passive: true
        peer_group: true
    INTERNAL:
        local_as: 65000
        peer_group: true
        remote_as: 65000
        shutdown: false
        update_source: 192.168.0.1
    172.16.0.2:
        remote_as: 65001
    192.168.0.2:
        peer_group: INTERNAL
quagga::bgp::address_families:
  ipv4_unicast:
    maximum_ebgp_paths: 2
    maximum_ibgp_paths: 10
    networks:
      - 1.1.1.0/24
      - 1.1.2.0/24
  ipv4_multicast:
    networks:
      - 230.0.0.0/24
      - 230.0.255.0/24
  ipv6_unicast:
    networks:
      - 1::/64
      - 2::/64
```

looks better?

**Comment by bibigon812** [comment]
Yes, it is.
I'm adding the resource quagga_bgp_peer_address_family.
```yaml
quagga::bgp::peers:
    INTERNAL:
        local_as: 65000
        peer_group: true
        remote_as: 65000
        shutdown: false
        update_source: 192.168.0.1
        address_family:
            ipv4_unicast:
                activate: true
                alliw_as_in: 1
                next_hop_self: true
```

**Comment by m4ce** [comment]
ok, let me push my changes first ...

**Comment by bibigon812** [comment]
Ok.

**Comment by bibigon812** [comment]
@m4ce What is the best way to describe address family params of bgp peers?
```yaml
quagga::bgp::peers:
    INTERNAL:
        local_as: 65000
        peer_group: true
        remote_as: 65000
        shutdown: false
        update_source: 192.168.0.1
        address_family:    # AF params start here
            ipv4_unicast:
                activate: true
                alliw_as_in: 1
                next_hop_self: true
            ipv4_multicast:
                activate: true
```

**Comment by m4ce** [comment]
I think we may want to keep the address family logic as a separate type and provider. It will be ugly to manage it in the same quagga_bgp_peer type/provider because of the nested structure.

**Comment by bibigon812** [comment]
@m4ce, Look [quagga_bgp_peer_address_family](https://github.com/bibigon812/bibigon812-quagga/blob/master/lib/puppet/type/quagga_bgp_peer_address_family.rb)

**Comment by m4ce** [comment]
I missed that :) - Yep, looks great! From a Hiera prospective, it's generally cleaner to match the data with what the resource type expects.

For instance:

```yaml
quagga::bgp::peer_address_families:
  "192.168.0.2 ipv4 unicast":
     peer_group: "INTERNAL"
     ..
```

**Comment by bibigon812** [comment]
@m4ce , Ok.

**Comment by bibigon812** [comment]
@m4ce How do you feel about creating a new class?

```puppet
class quagga::bgp::peer(
  Hash $address_families,
) {
  ...
}
```

```yaml
quagga::bgp::peer::address_families:
  ipv4_unicast:
    INTERNAL:
      peer_group: true
      next_hop_self: true
    192.168.0.2:
     peer_group: INTERNAL
```

I can do the transformation `{ 'ipv4_unicast' => { 'INTERNAL' => {...} } }` to `{ 'INTERNAL ipv4_unicast' => {...} }` in the class `quagga::bgp::peer`. But I don't know how to require the service `bgpd`.
