### ISSUE TITLE
Adding OSPF prefix substitution

### ISSUE THREAD

**Issue by linuxprofessor** [bibigon812/bibigon812-quagga#37]
I'm trying to use the quagga function to summarize a prefix and substitute it with another prefix (as described here: http://www.nongnu.org/quagga/docs/docs-multi/OSPF-area.html), but is seems this isn't possible today.

Example:
```
router ospf
   ospf router-id 172.16.26.25
   log-adjacency-changes detail
   network 192.168.14.0/24 area 0.0.0.121
   area 0.0.0.121 range 192.168.14.2/32 substitute 192.168.14.0/24
```
Would it be possible to add this without too much effort?

**Comment by bibigon812** [comment]
Hi, @linuxprofessor . Yes, I'll try to add it soon.

**Comment by bibigon812** [comment]
@linuxprofessor In 4.2.0:
```yaml
quagga::ospf::areas:
  0.0.0.121:
    networks:
      - 192.168.14.0/24
    ranges:
      192.168.14.2/32:
        substitute: 192.168.14.0/24
```
